"""Item-4 regression for the V4 build (KB id=4626): the citation-rate
counter over gate.log rows.

Exact expected counts on the corpus-derived fixture (priority 4114:
real-sample conformance + floor assertions, never fixtures authored from
belief). The fixture (tests/fixtures/v4_gate_log_corpus.jsonl, generated by
gen_v4_gate_log_corpus.py) carries two strata:
- 12 sanitized REAL rows from the live gate.log corpus (pre-capability
  schema → capability_missing path against the true historical format);
- 9 rows emitted by the REAL writer through run_gate with the model faked at
  the binary seam (citation-capability schema, known composition).

The counter implements docs/v4_citation_metric.md; label parity with the
gate contract is pinned here instead of importing gate at runtime.
"""
from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path

_TESTS = Path(__file__).resolve().parent
_SRC = _TESTS.parent / "src"
sys.path.insert(0, str(_SRC))

import v4_citation_rate as v4  # noqa: E402

FIXTURE = _TESTS / "fixtures" / "v4_gate_log_corpus.jsonl"


def _assert(cond, msg):
    if not cond:
        raise AssertionError(msg)


EXPECTED = {
    "rows_total": 21,
    "unparsable": 0,
    "non_gate": 0,
    "capability_missing": 12,
    "skipped": 1,
    "errored": 1,
    "invalid_recommendation": 0,
    "eligible": 7,
    "citing": 5,
    "changed_verdict": 3,
    "cited_proceed": 1,
    "cited_needs_human": 1,
    "citing_rate_pct": 71.43,
    "v4_firing_rate_pct": 42.86,
    "pass_threshold_pct": 5.0,
    "pass_at_5pct": True,
}


def test_exact_counts_on_corpus_fixture():
    out = v4.summarize([FIXTURE])
    for key, want in EXPECTED.items():
        _assert(
            out.get(key) == want,
            f"{key}: expected {want!r}, got {out.get(key)!r} (full: {out})",
        )
    _assert(out["files"] == 1, out["files"])
    print("PASS exact_counts_on_corpus_fixture")


def test_conformance_floor_on_real_schema_rows():
    # Floor assertions per priority 4114: every fixture row parses (0
    # unparsable) and all 12 real historical-schema rows are consumed and
    # bucketed, never silently dropped.
    out = v4.summarize([FIXTURE])
    _assert(out["unparsable"] == 0, out)
    _assert(out["capability_missing"] == 12, out)
    accounted = (
        out["unparsable"] + out["non_gate"] + out["capability_missing"]
        + out["skipped"] + out["errored"] + out["invalid_recommendation"]
        + out["eligible"]
    )
    _assert(
        accounted == out["rows_total"],
        f"buckets must partition rows exactly: {accounted} != {out['rows_total']}",
    )
    print("PASS conformance_floor_on_real_schema_rows")


def test_labels_match_gate_contract():
    import gate  # deliberate: parity check only, not a runtime dependency

    _assert(
        tuple(v4.CLASSIFIER_LABELS) == tuple(gate.CLASSIFIER_LABELS),
        f"label drift: {v4.CLASSIFIER_LABELS} vs {gate.CLASSIFIER_LABELS}",
    )
    _assert(
        v4.V4_CHANGED_LABELS == ("MODIFY", "DO_NOT_PROCEED"),
        f"changed-verdict labels must match docs/v4_citation_metric.md: "
        f"{v4.V4_CHANGED_LABELS}",
    )
    print("PASS labels_match_gate_contract")


def test_directory_mode_globs_gate_logs_only():
    tmp = Path(tempfile.mkdtemp(prefix="v4_counter_"))
    try:
        shutil.copy(FIXTURE, tmp / "gate-2026-01-01.log")
        (tmp / "adversary-2026-01-01.log").write_text(
            '{"event_type": "adversary"}\n', encoding="utf-8",
        )
        (tmp / "notes.txt").write_text("not a log\n", encoding="utf-8")
        out = v4.summarize(v4.resolve_paths([str(tmp)]))
        _assert(out["files"] == 1, f"must glob only gate-*.log: {out['files']}")
        _assert(out["rows_total"] == EXPECTED["rows_total"], out)
        _assert(out["eligible"] == EXPECTED["eligible"], out)
        _assert(
            out["v4_firing_rate_pct"] == EXPECTED["v4_firing_rate_pct"], out,
        )
        print("PASS directory_mode_globs_gate_logs_only")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_empty_input_and_degraded_rows():
    out = v4.summarize([])
    _assert(out["eligible"] == 0, out)
    _assert(out["citing_rate_pct"] is None, out)
    _assert(out["v4_firing_rate_pct"] is None, out)
    _assert(out["pass_at_5pct"] is None, out)

    tmp = Path(tempfile.mkdtemp(prefix="v4_counter_edge_"))
    try:
        p = tmp / "gate-2026-01-02.log"
        p.write_text(
            "not json\n"
            "[1, 2]\n"
            '{"event_type": "adversary", "surfaced_rejected_paths": []}\n',
            encoding="utf-8",
        )
        out2 = v4.summarize([p])
        _assert(out2["unparsable"] == 2, out2)
        _assert(out2["non_gate"] == 1, out2)
        _assert(out2["eligible"] == 0, out2)
        print("PASS empty_input_and_degraded_rows")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_cli_main_runs():
    rc = v4.main([str(FIXTURE)])
    _assert(rc == 0, rc)
    print("PASS cli_main_runs")


if __name__ == "__main__":
    test_exact_counts_on_corpus_fixture()
    test_conformance_floor_on_real_schema_rows()
    test_labels_match_gate_contract()
    test_directory_mode_globs_gate_logs_only()
    test_empty_input_and_degraded_rows()
    test_cli_main_runs()
