"""Item-4 regression for the V4 build (KB id=4626): the citation-rate
counter over gate.log rows.

Exact expected counts on the corpus-derived fixture (priority 4114:
real-sample conformance + floor assertions, never fixtures authored from
belief). The fixture (tests/fixtures/v4_gate_log_corpus.jsonl, generated by
gen_v4_gate_log_corpus.py) carries two strata:
- 12 sanitized REAL rows from the live gate.log corpus (pre-capability
  schema → capability_missing path against the true historical format);
- 9 rows emitted by the REAL writer through run_gate with the model faked at
  the binary seam (citation-capability schema, known composition).

The counter implements docs/v4_citation_metric.md; label parity with the
gate contract is pinned here instead of importing gate at runtime.
"""
from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path

_TESTS = Path(__file__).resolve().parent
_SRC = _TESTS.parent / "src"
sys.path.insert(0, str(_SRC))

import v4_citation_rate as v4  # noqa: E402

FIXTURE = _TESTS / "fixtures" / "v4_gate_log_corpus.jsonl"


def _assert(cond, msg):
    if not cond:
        raise AssertionError(msg)


EXPECTED = {
    "rows_total": 21,
    "unparsable": 0,
    "non_gate": 0,
    "capability_missing": 12,
    "skipped": 1,
    "errored": 1,
    "invalid_recommendation": 0,
    "eligible": 7,
    "citing": 5,
    # Founder-ratified 2026-08-09: cited NEEDS_HUMAN_JUDGMENT counts as a
    # changed verdict (return to 3948's literal "recommendation differs"
    # rubric). cited_needs_human remains reported so numerator composition
    # stays visible at read time.
    "changed_verdict": 4,
    "cited_proceed": 1,
    "cited_needs_human": 1,
    "citing_rate_pct": 71.43,
    "v4_firing_rate_pct": 57.14,
    "pass_threshold_pct": 5.0,
    "pass_at_5pct": True,
}


def test_exact_counts_on_corpus_fixture():
    out = v4.summarize([FIXTURE])
    for key, want in EXPECTED.items():
        _assert(
            out.get(key) == want,
            f"{key}: expected {want!r}, got {out.get(key)!r} (full: {out})",
        )
    _assert(out["files"] == 1, out["files"])
    print("PASS exact_counts_on_corpus_fixture")


def test_conformance_floor_on_real_schema_rows():
    # Floor assertions per priority 4114: every fixture row parses (0
    # unparsable) and all 12 real historical-schema rows are consumed and
    # bucketed, never silently dropped.
    out = v4.summarize([FIXTURE])
    _assert(out["unparsable"] == 0, out)
    _assert(out["capability_missing"] == 12, out)
    accounted = (
        out["unparsable"] + out["non_gate"] + out["capability_missing"]
        + out["skipped"] + out["errored"] + out["invalid_recommendation"]
        + out["eligible"]
    )
    _assert(
        accounted == out["rows_total"],
        f"buckets must partition rows exactly: {accounted} != {out['rows_total']}",
    )
    print("PASS conformance_floor_on_real_schema_rows")


def test_labels_match_gate_contract():
    import gate  # deliberate: parity check only, not a runtime dependency

    _assert(
        tuple(v4.CLASSIFIER_LABELS) == tuple(gate.CLASSIFIER_LABELS),
        f"label drift: {v4.CLASSIFIER_LABELS} vs {gate.CLASSIFIER_LABELS}",
    )
    _assert(
        v4.V4_CHANGED_LABELS == ("MODIFY", "DO_NOT_PROCEED", "NEEDS_HUMAN_JUDGMENT"),
        f"changed-verdict labels must match docs/v4_citation_metric.md "
        f"(founder-ratified NHJ inclusion, 2026-08-09): {v4.V4_CHANGED_LABELS}",
    )
    print("PASS labels_match_gate_contract")


def test_directory_mode_globs_gate_logs_only():
    tmp = Path(tempfile.mkdtemp(prefix="v4_counter_"))
    try:
        shutil.copy(FIXTURE, tmp / "gate-2026-01-01.log")
        (tmp / "adversary-2026-01-01.log").write_text(
            '{"event_type": "adversary"}\n', encoding="utf-8",
        )
        (tmp / "notes.txt").write_text("not a log\n", encoding="utf-8")
        out = v4.summarize(v4.resolve_paths([str(tmp)]))
        _assert(out["files"] == 1, f"must glob only gate-*.log: {out['files']}")
        _assert(out["rows_total"] == EXPECTED["rows_total"], out)
        _assert(out["eligible"] == EXPECTED["eligible"], out)
        _assert(
            out["v4_firing_rate_pct"] == EXPECTED["v4_firing_rate_pct"], out,
        )
        print("PASS directory_mode_globs_gate_logs_only")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_empty_input_and_degraded_rows():
    out = v4.summarize([])
    _assert(out["eligible"] == 0, out)
    _assert(out["citing_rate_pct"] is None, out)
    _assert(out["v4_firing_rate_pct"] is None, out)
    _assert(out["pass_at_5pct"] is None, out)

    tmp = Path(tempfile.mkdtemp(prefix="v4_counter_edge_"))
    try:
        p = tmp / "gate-2026-01-02.log"
        p.write_text(
            "not json\n"
            "[1, 2]\n"
            '{"event_type": "adversary", "surfaced_rejected_paths": []}\n',
            encoding="utf-8",
        )
        out2 = v4.summarize([p])
        _assert(out2["unparsable"] == 2, out2)
        _assert(out2["non_gate"] == 1, out2)
        _assert(out2["eligible"] == 0, out2)
        print("PASS empty_input_and_degraded_rows")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_cli_main_runs():
    rc = v4.main([str(FIXTURE)])
    _assert(rc == 0, rc)
    print("PASS cli_main_runs")


# Adversarial-panel hardenings (2026-08-08 panel over dd5f6f1; kept inside
# item 4's named scope: the fixture is item 4's deliverable and both counter
# fixes protect the declared metric arithmetic).

_HEX_SECRET_KEYS = ("attestation", "runtime_attestation", "runtime_version")


def test_fixture_carries_no_live_secret_shapes():
    """Sanitizer completeness: rows written by the installed V1 runtime carry
    attestation/HMAC material. The committed fixture must hold only fixture
    placeholders (prefix 'fx') in those slots, never live values."""
    import json as _json

    for line in FIXTURE.read_text(encoding="utf-8").splitlines():
        row = _json.loads(line)
        for key in _HEX_SECRET_KEYS:
            if key in row:
                _assert(
                    str(row[key]).startswith("fx"),
                    f"{key} not a fixture placeholder: {row[key]!r}",
                )
        proof = row.get("project_proof")
        if isinstance(proof, dict):
            for key in ("fingerprint", "key_id"):
                _assert(
                    str(proof.get(key, "fx")).startswith("fx"),
                    f"project_proof.{key} not a placeholder: {proof.get(key)!r}",
                )
            _assert(
                str(proof.get("key_epoch", "fx")).startswith("fx"),
                f"project_proof.key_epoch not a placeholder: {proof.get('key_epoch')!r}",
            )
        if "key_epoch" in row:
            _assert(
                str(row["key_epoch"]).startswith("fx"),
                f"key_epoch not a placeholder: {row['key_epoch']!r}",
            )
    print("PASS fixture_carries_no_live_secret_shapes")


def test_gz_aged_logs_are_counted():
    """log_utils retention gzips daily logs older than 30 days; a ~200-call
    window can span that, so the counter must read gate-*.log.gz too or the
    denominator silently shrinks."""
    import gzip

    tmp = Path(tempfile.mkdtemp(prefix="v4_counter_gz_"))
    try:
        raw = FIXTURE.read_bytes()
        with gzip.open(tmp / "gate-2026-01-01.log.gz", "wb") as fh:
            fh.write(raw)
        out = v4.summarize(v4.resolve_paths([str(tmp)]))
        _assert(out["files"] == 1, f"gz log not discovered: {out['files']}")
        _assert(out["rows_total"] == EXPECTED["rows_total"], out)
        _assert(out["eligible"] == EXPECTED["eligible"], out)
        print("PASS gz_aged_logs_are_counted")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_pass_threshold_uses_unrounded_rate():
    """docs/v4_citation_metric.md says PASS iff V4 >= 5.0 — on the true rate,
    not the 2-dp display rounding. 100/2001 = 4.9975% rounds to 5.0 but must
    NOT pass."""
    def _row(recommendation, cited):
        return {
            "event_type": "gate", "skipped": False, "error": None,
            "recommendation": recommendation,
            "surfaced_rejected_paths": [1] if cited else [],
            "cited_rejected_paths": [1] if cited else [],
        }

    rows = [_row("MODIFY", True) for _ in range(100)]
    rows += [_row("PROCEED", False) for _ in range(1901)]
    out = v4.compute(rows)
    _assert(out["eligible"] == 2001, out["eligible"])
    _assert(out["changed_verdict"] == 100, out["changed_verdict"])
    _assert(out["v4_firing_rate_pct"] == 5.0, out["v4_firing_rate_pct"])
    _assert(
        out["pass_at_5pct"] is False,
        f"4.9975% must not pass the 5.0 bar: {out['pass_at_5pct']}",
    )
    print("PASS pass_threshold_uses_unrounded_rate")


def test_eligibility_requires_skipped_exactly_false():
    """Codex review round 1 (2026-08-08) item-4 finding: the doc's eligibility
    conjunction is the strict `skipped == false`, but compute() used
    truthiness, so rows with skipped missing / null / 0 / "" counted as
    eligible. Only JSON false qualifies; every other value lands in the
    skipped bucket. (The real writer always emits a bool, so live counts are
    unchanged — this pins doc-code parity.)"""
    def _row(skipped_value, present=True):
        row = {
            "event_type": "gate", "error": None, "recommendation": "MODIFY",
            "surfaced_rejected_paths": [1], "cited_rejected_paths": [1],
        }
        if present:
            row["skipped"] = skipped_value
        return row

    out = v4.compute([
        _row(False),            # the only eligible shape
        _row(None),
        _row(0),
        _row(""),
        _row(True),
        _row(None, present=False),  # key missing entirely
    ])
    _assert(out["eligible"] == 1, f"only skipped==false is eligible: {out}")
    _assert(out["skipped"] == 5, f"all non-false shapes must bucket as skipped: {out}")
    _assert(out["changed_verdict"] == 1, out)
    print("PASS eligibility_requires_skipped_exactly_false")


if __name__ == "__main__":
    test_exact_counts_on_corpus_fixture()
    test_conformance_floor_on_real_schema_rows()
    test_labels_match_gate_contract()
    test_directory_mode_globs_gate_logs_only()
    test_empty_input_and_degraded_rows()
    test_cli_main_runs()
    test_fixture_carries_no_live_secret_shapes()
    test_gz_aged_logs_are_counted()
    test_pass_threshold_uses_unrounded_rate()
    test_eligibility_requires_skipped_exactly_false()
